spring:
  application:
    name: ecomerce_spring

#database information
datasource:
  URL: ${Database_url}
  USERNAME: ${Database_username}
  PASSWORD: ${Database_password}


#hibernate orm configuration
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format-sql: true